name: Publish package to the Maven Central Repository
on:
    push:
        branches:
            - feature/deployment
    release:
        types: [ created ]
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: Publish
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Maven Central Repository
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'adopt'
                    server-id: ossrh
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD
                    gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
                    gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}

            -   name: Publish package
                run: mvn -P  --batch-mode deploy
                env:
                    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
                    PERFORM_RELEASE: true
